# Generated by Django 4.0.6 on 2022-09-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ShoppingPrice',
            new_name='shippingPrice',
        ),
    ]
