# Generated by Django 4.0.6 on 2022-10-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catregory',
            new_name='category',
        ),
    ]
