# Generated by Django 4.0.6 on 2022-10-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_status_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='show',
        ),
    ]
