# Generated by Django 3.1.14 on 2022-11-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_review_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('validfrom', models.DateTimeField()),
                ('validto', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='order',
            name='copun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.copun'),
        ),
    ]
