# Generated by Django 3.1.14 on 2022-11-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_copun_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='copun',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='copun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.copun'),
        ),
    ]
