# Generated by Django 3.1.14 on 2022-11-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20221112_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copun',
            name='is_active',
        ),
    ]
